@api = http://localhost:3000

GET {{api}}/videos

### create video
POST {{api}}/videos
Content-Type: application/json

{
  "title": "Variables de Entorno en Node.js | dotenv & crossenv",
  "url": "https://www.youtube.com/watch?v=U6st9-lNUyY&t=480s"
}

### GET VIDEO
GET {{api}}/videos/625881eb1790732b0cf2b2c9

### DELETE VIDEO
DELETE {{api}}/videos/625882461790732b0cf2b2ca

### UPDATE
PUT {{api}}/videos/6258811a1790732b0cf2b2c8
Content-Type: application/json

{
  "title": "Variables de Entorno en Node.js | dotenv & crossenv",
  "url": "https://www.youtube.com/watch?v=U6st9-lNUyY&t=480s",
  "description": "the importance of enviroment variables"
}